// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qncxmhqjkgaclquqvftw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuY3htaHFqa2dhY2xxdXF2ZnR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzODQwNDUsImV4cCI6MjA2MDk2MDA0NX0.5DyLqnMIqoY9e2J8dkdRc0N7XcVSyrg4-K77Grc-f20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);